services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack edge port (all services)
      - "4571:4571"
    environment:
      - SERVICES=s3,dynamodb,sqs,lambda,iam,ec2,cloudwatch,route53 # List of services to start, you can customize this as needed
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - ./data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
