services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    environment:
      TZ: ${TZ:"Asia/Manila"}
      WEBPASSWORD: ${WEBPASSWORD:"Password123"}
      DNS1: ${DNS1:1.1.1.1}
      DNS2: ${DNS2:8.8.8.8}
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./data/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80" # Web interface
      - "8443:443" # Optional HTTPS
    restart: unless-stopped
