services:
  nessus:
    image: tenable/nessus:10.7.0-ubuntu
    container_name: nessus
    ports:
      - "8834:8834"
    restart: unless-stopped
    volumes:
      - nessus-data:/opt/nessus

volumes:
  nessus-data:
