services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API endpoint
      - "9001:9001" # Web console
    environment:
      - MINIO_ROOT_USER=admin # change this
      - MINIO_ROOT_PASSWORD=admin # change this
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    restart: unless-stopped
